#!/usr/bin/env php
<?
//$Id$

require_once("load_config.php");
require_once $LANG_CFG['classes_dir']."c_sync.php";
require_once $LANG_CFG['classes_dir']."c_utils.php";

function usage(){
	echo "Usage: ".$_SERVER['argv'][0]." [-r reference_file] [-d] <language files>\n";
	echo "\n";
	echo "Synchronize <language files> with reference file. That means that all phrasses\n";
	echo "from reference_file which miss in language file are added to it and all\n";
	echo "phrasses which miss in reference file are removed from language files.\n";
	echo "If reference file isn't specified, the default value is used.\n";
	echo "Prefix to dir with language files is automaticaly prepended.\n";
	echo "\n";
	echo "  -r reference_file  - file which are language files synchronized\n";
	echo "  -d                 - delete phrases which miss in reference file from\n";
	echo "                       language files. By default are these phrases moved to\n";
	echo "                       end.\n";
}


if ($_SERVER['argc'] < 2 || in_array($_SERVER['argv'][1], array('--help', '-help', '-h', '-?'))) {
	usage();
	exit (1);
}

$i=1;
$end = false;
$reference_file = $LANG_CFG['reference_file'];
$delete_phrases = false;

do{
	if (in_array($_SERVER['argv'][$i], array('-r'))) {
		if (empty($_SERVER['argv'][$i+1])){
			usage();
			exit (1);
		}
		else {
			$reference_file = $_SERVER['argv'][$i+1];
			$i+=2;
		}
	}
	elseif (in_array($_SERVER['argv'][$i], array('-d'))) {
		$delete_phrases = true;
		$i++;
	}
	else{
		$end = true;
	}
	

}while (!$end);

if (empty($_SERVER['argv'][$i])){
	usage();
	exit (1);
}

$sync = new Csync($LANG_CFG['lang_dir'].$reference_file);
if ($delete_phrases) $sync->delete_unused_phrases = true;

for(; $i<count($_SERVER['argv']); $i++){

	$path =  $LANG_CFG['lang_dir'].$_SERVER['argv'][$i];
	$filenames = glob($path, GLOB_NOCHECK);

	foreach($filenames as $file){
		$ffile = realpath($file);
		if ($ffile === false){
	 		Cutils::error_report("File ".$file." doesn't exists. Exiting...");
		}

		echo "Synchronizing file: ".basename($ffile)."\n";

		$sync->sync($ffile);
		echo "\n";
	}

}

?>
